// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/post/post.proto

package go_micro_srv_post

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Post struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	CreatedTime          uint64   `protobuf:"varint,4,opt,name=createdTime,proto3" json:"createdTime,omitempty"`
	UpdatedTime          uint64   `protobuf:"varint,5,opt,name=updatedTime,proto3" json:"updatedTime,omitempty"`
	UserID               int64    `protobuf:"varint,6,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Post) Reset()         { *m = Post{} }
func (m *Post) String() string { return proto.CompactTextString(m) }
func (*Post) ProtoMessage()    {}
func (*Post) Descriptor() ([]byte, []int) {
	return fileDescriptor_post_c93c6777f85364c5, []int{0}
}
func (m *Post) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Post.Unmarshal(m, b)
}
func (m *Post) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Post.Marshal(b, m, deterministic)
}
func (dst *Post) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Post.Merge(dst, src)
}
func (m *Post) XXX_Size() int {
	return xxx_messageInfo_Post.Size(m)
}
func (m *Post) XXX_DiscardUnknown() {
	xxx_messageInfo_Post.DiscardUnknown(m)
}

var xxx_messageInfo_Post proto.InternalMessageInfo

func (m *Post) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Post) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Post) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Post) GetCreatedTime() uint64 {
	if m != nil {
		return m.CreatedTime
	}
	return 0
}

func (m *Post) GetUpdatedTime() uint64 {
	if m != nil {
		return m.UpdatedTime
	}
	return 0
}

func (m *Post) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Detail               string   `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_post_c93c6777f85364c5, []int{1}
}
func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (dst *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(dst, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

type Request struct {
	PostID               string   `protobuf:"bytes,1,opt,name=postID,proto3" json:"postID,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	UserID               int64    `protobuf:"varint,3,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_post_c93c6777f85364c5, []int{2}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetPostID() string {
	if m != nil {
		return m.PostID
	}
	return ""
}

func (m *Request) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Request) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

type Response struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                *Error   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Post                 *Post    `protobuf:"bytes,3,opt,name=post,proto3" json:"post,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_post_c93c6777f85364c5, []int{3}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *Response) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Response) GetPost() *Post {
	if m != nil {
		return m.Post
	}
	return nil
}

func init() {
	proto.RegisterType((*Post)(nil), "go.micro.srv.post.post")
	proto.RegisterType((*Error)(nil), "go.micro.srv.post.Error")
	proto.RegisterType((*Request)(nil), "go.micro.srv.post.Request")
	proto.RegisterType((*Response)(nil), "go.micro.srv.post.Response")
}

func init() { proto.RegisterFile("proto/post/post.proto", fileDescriptor_post_c93c6777f85364c5) }

var fileDescriptor_post_c93c6777f85364c5 = []byte{
	// 318 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0x4d, 0x4b, 0x03, 0x31,
	0x10, 0x35, 0xed, 0x6e, 0x3f, 0xa6, 0x50, 0x30, 0xf8, 0x11, 0xea, 0x65, 0xd9, 0x53, 0x41, 0x88,
	0xd0, 0xfe, 0x85, 0x7a, 0x28, 0x1e, 0xd4, 0xa8, 0x3f, 0xa0, 0x26, 0x83, 0x04, 0xda, 0x66, 0x4d,
	0xb2, 0x82, 0x47, 0xff, 0x8a, 0xbf, 0x54, 0x32, 0xbb, 0xd5, 0x8a, 0xf5, 0x12, 0xf2, 0x5e, 0xde,
	0xcc, 0xbe, 0x37, 0xb3, 0x70, 0x5a, 0x79, 0x17, 0xdd, 0x55, 0xe5, 0x42, 0xa4, 0x43, 0x12, 0xe6,
	0xc7, 0x2f, 0x4e, 0x6e, 0xac, 0xf6, 0x4e, 0x06, 0xff, 0x26, 0xd3, 0x43, 0xf9, 0xc9, 0x20, 0x4b,
	0x17, 0x3e, 0x86, 0x8e, 0x35, 0x82, 0x15, 0x6c, 0xda, 0x55, 0x1d, 0x6b, 0xf8, 0x09, 0xe4, 0xd1,
	0xc6, 0x35, 0x8a, 0x4e, 0xc1, 0xa6, 0x43, 0xd5, 0x00, 0x2e, 0xa0, 0xaf, 0xdd, 0x36, 0xe2, 0x36,
	0x8a, 0x2e, 0xf1, 0x3b, 0xc8, 0x0b, 0x18, 0x69, 0x8f, 0xab, 0x88, 0xe6, 0xd1, 0x6e, 0x50, 0x64,
	0x05, 0x9b, 0x66, 0x6a, 0x9f, 0x4a, 0x8a, 0xba, 0x32, 0xdf, 0x8a, 0xbc, 0x51, 0xec, 0x51, 0xfc,
	0x0c, 0x7a, 0x75, 0x40, 0xbf, 0x5c, 0x88, 0x1e, 0xf9, 0x68, 0x51, 0x39, 0x87, 0xfc, 0xda, 0x7b,
	0xe7, 0x39, 0x87, 0x4c, 0x3b, 0x83, 0x64, 0x33, 0x57, 0x74, 0x4f, 0x45, 0x06, 0xe3, 0xca, 0xae,
	0x5b, 0xa7, 0x2d, 0x2a, 0x6f, 0xa1, 0xaf, 0xf0, 0xb5, 0xc6, 0x10, 0x93, 0x24, 0x65, 0x5c, 0x2e,
	0xa8, 0x70, 0xa8, 0x5a, 0xf4, 0x4f, 0xc6, 0x1f, 0x17, 0xdd, 0x5f, 0x2e, 0x3e, 0x18, 0x0c, 0x14,
	0x86, 0xca, 0x6d, 0x03, 0x0d, 0x22, 0xd4, 0x5a, 0x63, 0x08, 0xd4, 0x73, 0xa0, 0x76, 0x90, 0x4b,
	0xc8, 0x31, 0x99, 0xa5, 0xa6, 0xa3, 0x99, 0x90, 0x7f, 0x86, 0x2e, 0x29, 0x8c, 0x6a, 0x64, 0xfc,
	0xb2, 0x59, 0x00, 0x7d, 0x6c, 0x34, 0x3b, 0x3f, 0x20, 0x4f, 0x87, 0x22, 0xd1, 0xec, 0x01, 0xb2,
	0xbb, 0xb4, 0xad, 0x1b, 0x18, 0xdf, 0xd7, 0xe8, 0xdf, 0x9f, 0x02, 0xfa, 0x44, 0x04, 0x3e, 0x39,
	0x50, 0xd8, 0xe6, 0x9f, 0x5c, 0x1c, 0x7c, 0x6b, 0x92, 0x94, 0x47, 0xcf, 0x3d, 0xfa, 0x3b, 0xe6,
	0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x89, 0xd1, 0x27, 0x2d, 0x36, 0x02, 0x00, 0x00,
}
